apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: example-vmagent
    app.kubernetes.io/name: vmagent
    managed-by: vm-operator
  name: vmagent-example-vmagent
  namespace: monitoring
  ownerReferences:
    - apiVersion: operator.victoriametrics.com/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: VMAgent
      name: example-vmagent
      uid: 9b589049-3e19-409f-b056-e334c680c99d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: example-vmagent
      app.kubernetes.io/name: vmagent
      managed-by: vm-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: monitoring
        app.kubernetes.io/instance: example-vmagent
        app.kubernetes.io/name: vmagent
        managed-by: vm-operator
    spec:
      containers:
        - args:
            - -httpListenAddr=:8429
            - -promscrape.config=/etc/vmagent/config_out/vmagent.env.yaml
            - -remoteWrite.maxDiskUsagePerURL=1073741824
            - -remoteWrite.tmpDataPath=/tmp/vmagent-remotewrite-data
            - -remoteWrite.url=http://vminsert-example-vmcluster-persistent.monitoring.svc.cluster.local:8480/insert/0/prometheus/api/v1/write
          image: victoriametrics/vmagent:v1.83.1
#          image: victoriametrics/vmagent:v1.63.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 8429
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          name: vmagent
          ports:
            - containerPort: 8429
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 8429
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /tmp/vmagent-remotewrite-data
              name: persistent-queue-data
            - mountPath: /etc/vmagent/config_out
              name: config-out
              readOnly: true
            - mountPath: /etc/vmagent-tls/certs
              name: tls-assets
              readOnly: true
            - mountPath: /etc/vm/relabeling
              name: relabeling-assets
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: vmagent-example-vmagent
      serviceAccountName: vmagent-example-vmagent
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: persistent-queue-data
        - name: config
          secret:
            defaultMode: 420
            secretName: vmagent-example-vmagent
        - name: tls-assets
          secret:
            defaultMode: 420
            secretName: tls-assets-vmagent-example-vmagent
        - emptyDir: {}
          name: config-out
        - configMap:
            defaultMode: 420
            name: relabelings-assets-vmagent-example-vmagent
          name: relabeling-assets