---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: example-vmcluster-persistent
spec:
  retentionPeriod: "12"
  vmstorage:
    replicaCount: 1
  vmselect:
    replicaCount: 1
  vminsert:
    replicaCount: 1
#---
#apiVersion: operator.victoriametrics.com/v1beta1
#kind: VMAgent
#metadata:
#  name: example-vmagent
#spec:
#  serviceScrapeNamespaceSelector: {}
#  podScrapeNamespaceSelector: {}
#  podScrapeSelector: {}
#  serviceScrapeSelector: {}
#  nodeScrapeSelector: {}
#  nodeScrapeNamespaceSelector: {}
#  staticScrapeSelector: {}
#  staticScrapeNamespaceSelector: {}
#  replicaCount: 1
#  serviceAccountName: prometheus-k8s
#  remoteWrite:
#    - url: "http://vminsert-example-vmcluster-persistent.monitoring.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"


#---
#apiVersion: operator.victoriametrics.com/v1beta1
#kind: VMAgent
#metadata:
#  name: vm-vmagent
#spec:
#  selectAllByDefault: true
#  podMetadata:
#    labels:
#      victoriaMetrics: vmagent
#  replicaCount: 1
#  serviceAccountName: vmagent
#  image:
#    pullPolicy: IfNotPresent
##    repository: images.huazai.com/release/vmagent
##    tag: v1.63.0-cluster
#    tag: v1.63.0
#  extraArgs:
#    memory.allowedPercent: "40"
#  remoteWrite:
#    - url: "http://vminsert-example-vmcluster-persistent.monitoring.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"
