apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: example-vmagent
    app.kubernetes.io/name: vmagent
    managed-by: vm-operator
  name: tls-assets-vmagent-example-vmagent
  namespace: monitoring
  ownerReferences:
    - apiVersion: operator.victoriametrics.com/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: VMAgent
      name: example-vmagent
      uid: 9b589049-3e19-409f-b056-e334c680c99d
type: Opaque