# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "D:\\server_files", "/local_file"
  config.vm.provider "vmware_workstation" do |vb|
    vb.gui = false
    vb.memory = 8192
    vb.cpus = 4
  end
  config.vm.provision "shell", inline: <<-SHELL
    echo "sudo su -" >> .bashrc
  SHELL
  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname="node#{i}"
      config.vm.provider "vmware_workstation" do |vb|
        vb.gui = false
        vb.memory = 2048
        vb.cpus = 1
      end
    end
  end

  (4..6).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname="node#{i}"
    end
  end

end